// Flat list of country names used by some components for simple select lists
export const COUNTRIES = [
  "Afghanistan",
  "Albania",
  "Algeria",
  "Andorra",
  "Angola",
  "Antigua and Barbuda",
  "Argentina",
  "Armenia",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bhutan",
  "Bolivia",
  "Bosnia and Herzegovina",
  "Botswana",
  "Brazil",
  "Brunei",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cabo Verde",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Central African Republic",
  "Chad",
  "Chile",
  "China",
  "Colombia",
  "Comoros",
  "Congo",
  "Costa Rica",
  "Croatia",
  "Cuba",
  "Cyprus",
  "Czech Republic",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Eritrea",
  "Estonia",
  "Eswatini",
  "Ethiopia",
  "Fiji",
  "Finland",
  "France",
  "Gabon",
  "Gambia",
  "Georgia",
  "Germany",
  "Ghana",
  "Greece",
  "Grenada",
  "Guatemala",
  "Guinea",
  "Guinea-Bissau",
  "Guyana",
  "Haiti",
  "Honduras",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran",
  "Iraq",
  "Ireland",
  "Israel",
  "Italy",
  "Jamaica",
  "Japan",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Kuwait",
  "Kyrgyzstan",
  "Laos",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Marshall Islands",
  "Mauritania",
  "Mauritius",
  "Mexico",
  "Micronesia",
  "Moldova",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Morocco",
  "Mozambique",
  "Myanmar",
  "Namibia",
  "Nauru",
  "Nepal",
  "Netherlands",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "North Korea",
  "North Macedonia",
  "Norway",
  "Oman",
  "Pakistan",
  "Palau",
  "Palestine",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Poland",
  "Portugal",
  "Qatar",
  "Romania",
  "Russia",
  "Rwanda",
  "Saint Kitts and Nevis",
  "Saint Lucia",
  "Saint Vincent and the Grenadines",
  "Samoa",
  "San Marino",
  "Sao Tome and Principe",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Slovakia",
  "Slovenia",
  "Solomon Islands",
  "Somalia",
  "South Africa",
  "South Korea",
  "South Sudan",
  "Spain",
  "Sri Lanka",
  "Sudan",
  "Suriname",
  "Sweden",
  "Switzerland",
  "Syria",
  "Taiwan",
  "Tajikistan",
  "Tanzania",
  "Thailand",
  "Timor-Leste",
  "Togo",
  "Tonga",
  "Trinidad and Tobago",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Tuvalu",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "United States",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Vatican City",
  "Venezuela",
  "Vietnam",
  "Yemen",
  "Zambia",
  "Zimbabwe",
] as const

export type Country = typeof COUNTRIES[number]

// Rich country list with ISO alpha-2 code and international dial code
// Used by user forms for phone formatting and flag rendering
export const countries = [
  { name: "United States", code: "US", dial_code: "+1" },
  { name: "United Kingdom", code: "GB", dial_code: "+44" },
  { name: "Canada", code: "CA", dial_code: "+1" },
  { name: "Germany", code: "DE", dial_code: "+49" },
  { name: "France", code: "FR", dial_code: "+33" },
  { name: "Italy", code: "IT", dial_code: "+39" },
  { name: "Spain", code: "ES", dial_code: "+34" },
  { name: "Netherlands", code: "NL", dial_code: "+31" },
  { name: "Sweden", code: "SE", dial_code: "+46" },
  { name: "Switzerland", code: "CH", dial_code: "+41" },
  { name: "Australia", code: "AU", dial_code: "+61" },
  { name: "New Zealand", code: "NZ", dial_code: "+64" },
  { name: "China", code: "CN", dial_code: "+86" },
  { name: "Japan", code: "JP", dial_code: "+81" },
  { name: "India", code: "IN", dial_code: "+91" },
  { name: "Pakistan", code: "PK", dial_code: "+92" },
  { name: "Bangladesh", code: "BD", dial_code: "+880" },
  { name: "Turkey", code: "TR", dial_code: "+90" },
  { name: "Saudi Arabia", code: "SA", dial_code: "+966" },
  { name: "United Arab Emirates", code: "AE", dial_code: "+971" },
  { name: "Qatar", code: "QA", dial_code: "+974" },
  { name: "Kuwait", code: "KW", dial_code: "+965" },
  { name: "Bahrain", code: "BH", dial_code: "+973" },
  { name: "Oman", code: "OM", dial_code: "+968" },
  { name: "Jordan", code: "JO", dial_code: "+962" },
  { name: "Lebanon", code: "LB", dial_code: "+961" },
  { name: "Palestine", code: "PS", dial_code: "+970" },
  { name: "Egypt", code: "EG", dial_code: "+20" },
  { name: "Morocco", code: "MA", dial_code: "+212" },
  { name: "Algeria", code: "DZ", dial_code: "+213" },
  { name: "Tunisia", code: "TN", dial_code: "+216" },
  { name: "South Africa", code: "ZA", dial_code: "+27" },
  { name: "Nigeria", code: "NG", dial_code: "+234" },
  { name: "Kenya", code: "KE", dial_code: "+254" },
  { name: "Ghana", code: "GH", dial_code: "+233" },
  { name: "Russia", code: "RU", dial_code: "+7" },
  { name: "Ukraine", code: "UA", dial_code: "+380" },
  { name: "Poland", code: "PL", dial_code: "+48" },
  { name: "Portugal", code: "PT", dial_code: "+351" },
  { name: "Greece", code: "GR", dial_code: "+30" },
  { name: "Romania", code: "RO", dial_code: "+40" },
  { name: "Czech Republic", code: "CZ", dial_code: "+420" },
  { name: "Hungary", code: "HU", dial_code: "+36" },
  { name: "Austria", code: "AT", dial_code: "+43" },
  { name: "Ireland", code: "IE", dial_code: "+353" },
  { name: "Denmark", code: "DK", dial_code: "+45" },
  { name: "Norway", code: "NO", dial_code: "+47" },
  { name: "Finland", code: "FI", dial_code: "+358" },
  { name: "Belgium", code: "BE", dial_code: "+32" },
  { name: "Luxembourg", code: "LU", dial_code: "+352" },
  { name: "Mexico", code: "MX", dial_code: "+52" },
  { name: "Brazil", code: "BR", dial_code: "+55" },
  { name: "Argentina", code: "AR", dial_code: "+54" },
  { name: "Chile", code: "CL", dial_code: "+56" },
  { name: "Colombia", code: "CO", dial_code: "+57" },
  { name: "Peru", code: "PE", dial_code: "+51" },
  { name: "Venezuela", code: "VE", dial_code: "+58" },
  { name: "Malaysia", code: "MY", dial_code: "+60" },
  { name: "Singapore", code: "SG", dial_code: "+65" },
  { name: "Philippines", code: "PH", dial_code: "+63" },
  { name: "Indonesia", code: "ID", dial_code: "+62" },
  { name: "Thailand", code: "TH", dial_code: "+66" },
  { name: "Vietnam", code: "VN", dial_code: "+84" },
  { name: "Sri Lanka", code: "LK", dial_code: "+94" },
] as const

export const getCountryOptions = () => {
  return COUNTRIES.map(country => ({
    value: country,
    label: country,
  }))
}