import {
  Users,
  Grid,
  Ticket,
  User,
  Shield,
  LogOut,
  Bell,
  Plus,
  Search,
  Filter,
  ChevronLeft,
  ChevronRight,
  MoreVertical,
  Edit,
  Trash,
  UserX,
  Loader2,
} from "lucide-react"

export const Icons = {
  users: Users,
  categories: Grid,
  cashback: Ticket,
  profile: User,
  admins: Shield,
  logout: LogOut,
  notification: Bell,
  add: Plus,
  search: Search,
  filter: Filter,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  moreVertical: MoreVertical,
  edit: Edit,
  trash: Trash,
  userX: UserX,
  spinner: Loader2,
}
